#!/bin/sh

# Arquivo para verificar se dois diretorios possuem o mesmo numero de arquivos.
# Uso: Usado para verificar se a cópia foi bem sucedida de um diretório para outro

diretorio1=$1
diretorio2=$2

if [ ! -d $diretorio1 ]; then
	echo "Diretorio do primeiro argumento é invalido"
	exit 1
fi

if [ ! -d ${diretorio2} ]; then
	echo "Diretorio do segundo argumento é invalido"
	exit 1
fi

for i in $(ls $diretorio1); do
	
	if [ -d "${diretorio2}/${i}" ]; then
		dir_para_ser_comparado="${diretorio1}/${i}"
		dir_para_comparar="${diretorio2}/${i}"
		
		qtd_arquivos_dir1=$(find ${dir_para_ser_comparado} -type f | wc -l)
		qtd_arquivos_dir2=$(find ${dir_para_comparar} -type f | wc -l)
		
		if [ $qtd_arquivos_dir1 -eq $qtd_arquivos_dir2 ]; then
			echo "Integridade da copia OK - Os dois arquivos possuem o sub-diretorio ${i} e a mesma quantidade de arquivos."
		else
			echo "Integridade da copia AVARIADO - Os dois arquivos possuem o sub-diretorio ${i} mas não a mesma quantidade de arquivos"
		fi

	else
		echo "O diretório ${i} está presente em ${diretorio1} mas não em ${diretorio2}"
	fi
done

