#!/bin/sh

# Shell script para ligar o libvirtd para o QEMU

if $(lsmod | grep -Eq "^kvm\b"); then
	echo "Modulo KVM - Carregado"
else
	echo "Primeiro, carregue o modulo KVM em seu kernel."
	exit 1
fi

if [ $(sudo systemctl is-active libvirtd) = "inactive" ]; then
	
	sudo systemctl start libvirtd

	echo "libvirtd ativado e pronto para uso!!"
else
	echo "libvirtd já está ativo!!";
	exit 1;
fi

